# Generated by Django 5.0.7 on 2024-07-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_dimensions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='meta',
        ),
        migrations.AddField(
            model_name='product',
            name='maximum_order_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
