# Generated by Django 5.0.7 on 2024-07-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_meta_product_maximum_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_class',
        ),
    ]
