# Generated by Django 5.0.7 on 2024-07-17 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_availability_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductVariant',
            new_name='ProductVariants',
        ),
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='VariantImages',
        ),
    ]
