# Generated by Django 5.0.7 on 2024-07-19 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_productvariant_productvariants_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariants',
            old_name='name',
            new_name='variant_name',
        ),
        migrations.RemoveField(
            model_name='variantimages',
            name='product',
        ),
        migrations.AddField(
            model_name='variantimages',
            name='product_variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.productvariants'),
            preserve_default=False,
        ),
    ]
