# Generated by Django 5.0.7 on 2024-07-20 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_name_productvariants_variant_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Dimensions',
        ),
    ]
