# Generated by Django 5.0.7 on 2024-07-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_delete_brand_delete_dimensions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
