# Generated by Django 5.0.7 on 2024-07-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_stock_product_remove_stock_warehouse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meta',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='meta',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='meta',
            name='metadata',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
