# Generated by Django 5.0.7 on 2024-07-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_meta_barcode_remove_meta_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name': 'Product Attribute', 'verbose_name_plural': 'Product Attributes'},
        ),
        migrations.AlterModelOptions(
            name='productvariants',
            options={'verbose_name': 'Product Variant', 'verbose_name_plural': 'Product Variants'},
        ),
        migrations.AlterModelOptions(
            name='variantimages',
            options={'verbose_name': 'Variant Image', 'verbose_name_plural': 'Variant Images'},
        ),
    ]
