# Generated by Django 5.0.7 on 2024-07-24 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_options_alter_productattribute_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.meta'),
        ),
    ]
