# Generated by Django 5.0.7 on 2024-07-24 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='meta',
        ),
        migrations.AddField(
            model_name='product',
            name='metadata',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.meta'),
        ),
    ]
