# Generated by Django 5.0.7 on 2024-07-24 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_product_meta_product_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='metadata',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_meta', to='product.meta'),
        ),
    ]
