# Generated by Django 5.0.7 on 2024-07-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_product_metadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='metadata',
            new_name='meta_data',
        ),
    ]
