# Generated by Django 5.0.7 on 2024-08-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_rename_hidden_product_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productvariants',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
