# Generated by Django 5.0.7 on 2024-08-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_productvariants_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariants',
            old_name='quantity',
            new_name='variant_quantity',
        ),
    ]
