# Generated by Django 5.0.7 on 2024-08-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_rename_quantity_productvariants_variant_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariants',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
