# Generated by Django 5.0.7 on 2024-10-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_alter_productvariants_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability_status',
        ),
        migrations.RemoveField(
            model_name='productvariants',
            name='availability_status',
        ),
    ]
