# Generated by Django 5.0.7 on 2024-10-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_remove_product_availability_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='maximum_order_quantity',
            field=models.CharField(default=5, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_order_quantity',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.tag'),
        ),
        migrations.AlterField(
            model_name='productvariants',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
