# Generated by Django 5.0.7 on 2024-07-16 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent_category', 'category_name']},
        ),
    ]
