# Generated by Django 5.0.7 on 2024-07-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent_category__id']},
        ),
    ]
