# Generated by Django 5.0.7 on 2024-08-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='hidden',
            new_name='is_active',
        ),
    ]
