# Generated by Django 5.0.7 on 2024-08-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_rename_hidden_category_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
