# Generated by Django 5.0.7 on 2024-07-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], max_length=10),
        ),
    ]
