# Generated by Django 5.0.7 on 2024-07-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_user_address_address_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_address',
            old_name='street_address',
            new_name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='user_address',
            name='apartment_name',
        ),
        migrations.RemoveField(
            model_name='user_address',
            name='house_name',
        ),
        migrations.AddField(
            model_name='user_address',
            name='address_line_2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
