# Generated by Django 5.0.7 on 2024-08-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['created_date']},
        ),
    ]
