# Generated by Django 5.0.7 on 2024-08-07 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
