# Generated by Django 5.0.7 on 2024-08-07 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cartitem_variant_id'),
        ('product', '0018_alter_product_meta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='cart.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='variant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productvariants'),
        ),
    ]
