# Generated by Django 5.0.7 on 2024-08-17 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_cartitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variant_id',
            new_name='variant',
        ),
    ]
