# Generated by Django 5.0.7 on 2024-08-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_cartitem_created_at_cartitem_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
