# Generated by Django 5.0.7 on 2024-07-27 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_order_id'),
        ('product', '0018_alter_product_meta_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('variant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productvariants')),
            ],
        ),
    ]
