# Generated by Django 5.0.7 on 2024-08-02 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_orderitem_order_id'),
        ('product', '0018_alter_product_meta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='variant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants_items', to='product.productvariants'),
        ),
    ]
