# Generated by Django 5.0.7 on 2024-08-05 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('order', '0010_alter_orderitem_variant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_id',
            field=models.ForeignKey(default='45a3c1d6-9423-4082-8b4e-af23785786e3', on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
            preserve_default=False,
        ),
    ]
